version: "3.4"
services:
  redis:
    image: redis
    command: ["redis-server","--cluster-enabled yes","--cluster-node-timeout 60000","--cluster-require-full-coverage no"]
    ports:
      - 6379:6379
    deploy:
      replicas: 6
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure